// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	admin "github.com/SnakeHacker/deepkg/admin/internal/handler/admin"
	document "github.com/SnakeHacker/deepkg/admin/internal/handler/document"
	document_dir "github.com/SnakeHacker/deepkg/admin/internal/handler/document_dir"
	file "github.com/SnakeHacker/deepkg/admin/internal/handler/file"
	org "github.com/SnakeHacker/deepkg/admin/internal/handler/org"
	schema_ontology "github.com/SnakeHacker/deepkg/admin/internal/handler/schema_ontology"
	schema_ontology_prop "github.com/SnakeHacker/deepkg/admin/internal/handler/schema_ontology_prop"
	schema_triple "github.com/SnakeHacker/deepkg/admin/internal/handler/schema_triple"
	user "github.com/SnakeHacker/deepkg/admin/internal/handler/user"
	"github.com/SnakeHacker/deepkg/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: admin.HealthHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/document/get",
				Handler: document.GetDocumentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/document/list",
				Handler: document.GetDocumentListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/document/create",
				Handler: document.CreateDocumentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/document/update",
				Handler: document.UpdateDocumentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/document/delete",
				Handler: document.DeleteDocumentsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/document_dir/get",
				Handler: document_dir.GetDocumentDirHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/document_dir/list",
				Handler: document_dir.GetDocumentDirListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/document_dir/create",
				Handler: document_dir.CreateDocumentDirHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/document_dir/update",
				Handler: document_dir.UpdateDocumentDirHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/document_dir/delete",
				Handler: document_dir.DeleteDocumentDirsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/file/upload",
				Handler: file.UploadFileHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/org/get",
				Handler: org.GetOrgHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/org/list",
				Handler: org.GetOrgListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/org/create",
				Handler: org.CreateOrgHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/org/update",
				Handler: org.UpdateOrgHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/org/delete",
				Handler: org.DeleteOrgsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/schema_ontology/get",
				Handler: schema_ontology.GetSchemaOntologyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/schema_ontology/list",
				Handler: schema_ontology.GetSchemaOntologyListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/schema_ontology/create",
				Handler: schema_ontology.CreateSchemaOntologyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/schema_ontology/update",
				Handler: schema_ontology.UpdateSchemaOntologyHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/schema_ontology/delete",
				Handler: schema_ontology.DeleteSchemaOntologysHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/schema_ontology_prop/get",
				Handler: schema_ontology_prop.GetSchemaOntologyPropHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/schema_ontology_prop/list",
				Handler: schema_ontology_prop.GetSchemaOntologyPropListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/schema_ontology_prop/create",
				Handler: schema_ontology_prop.CreateSchemaOntologyPropHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/schema_ontology_prop/update",
				Handler: schema_ontology_prop.UpdateSchemaOntologyPropHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/schema_ontology_prop/delete",
				Handler: schema_ontology_prop.DeleteSchemaOntologyPropsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/schema_triple/get",
				Handler: schema_triple.GetSchemaTripleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/schema_triple/list",
				Handler: schema_triple.GetSchemaTripleListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/schema_triple/create",
				Handler: schema_triple.CreateSchemaTripleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/schema_triple/update",
				Handler: schema_triple.UpdateSchemaTripleHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/schema_triple/delete",
				Handler: schema_triple.DeleteSchemaTriplesHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/user/get",
				Handler: user.GetUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/list",
				Handler: user.GetUserListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/create",
				Handler: user.CreateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/update",
				Handler: user.UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/delete",
				Handler: user.DeleteUsersHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api"),
	)
}
