// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.4

package types

type CreateDocumentDirReq struct {
	DocumentDir DocumentDir `json:"document_dir"`
}

type CreateDocumentReq struct {
	Document Document `json:"document"`
}

type CreateEntityReq struct {
	Entity Entity `json:"entity"`
}

type CreateExtractTaskReq struct {
	ExtractTask ExtractTask `json:"extract_task"`
}

type CreateKnowledgeGraphWorkspaceReq struct {
	KnowledgeGraphWorkspace KnowledgeGraphWorkspace `json:"knowledge_graph_workspace"`
}

type CreateOrgReq struct {
	Organization Organization `json:"organization"`
}

type CreatePropReq struct {
	Prop EntityProp `json:"prop"`
}

type CreateRelationshipReq struct {
	Relationship Relationship `json:"relationship"`
}

type CreateSchemaOntologyPropReq struct {
	SchemaOntologyProp SchemaOntologyProp `json:"schema_ontology_prop"`
}

type CreateSchemaOntologyReq struct {
	SchemaOntology SchemaOntology `json:"schema_ontology"`
}

type CreateSchemaTripleReq struct {
	SchemaTriple SchemaTriple `json:"schema_triple"`
}

type CreateUserReq struct {
	User User `json:"user"`
}

type DeleteDocumentDirsReq struct {
	IDs []int64 `json:"ids"`
}

type DeleteDocumentsReq struct {
	IDs []int64 `json:"ids"`
}

type DeleteEntitiesReq struct {
	IDs []int64 `json:"ids"`
}

type DeleteExtractTasksReq struct {
	IDs []int64 `json:"ids"`
}

type DeleteKnowledgeGraphWorkspacesReq struct {
	IDs []int64 `json:"ids"`
}

type DeleteOrgsReq struct {
	Ids []int64 `json:"ids"`
}

type DeletePropsReq struct {
	IDs []int64 `json:"ids"`
}

type DeleteRelationshipsReq struct {
	IDs []int64 `json:"ids"`
}

type DeleteSchemaOntologyPropsReq struct {
	IDs []int64 `json:"ids"`
}

type DeleteSchemaOntologysReq struct {
	IDs []int64 `json:"ids"`
}

type DeleteSchemaTriplesReq struct {
	IDs []int64 `json:"ids"`
}

type DeleteUsersReq struct {
	Ids []int64 `json:"ids"`
}

type Document struct {
	ID          int64  `json:"id, optional"`
	DocName     string `json:"doc_name"`
	DocDesc     string `json:"doc_desc"`
	DocPath     string `json:"doc_path"`
	DirID       int64  `json:"dir_id"`
	CreatorID   int64  `json:"creator_id,optional"`
	CreatorName string `json:"creator_name,optional"`
	CreatedAt   string `json:"created_at,optional"`
	UpdatedAt   string `json:"updated_at,optional"`
}

type DocumentDir struct {
	ID        int64         `json:"id, optional"`
	DirName   string        `json:"dir_name"`
	ParentID  int64         `json:"parent_id"`
	Children  []DocumentDir `json:"children"`
	SortIndex int           `json:"sort_index"`
	Remark    string        `json:"remark"`
	CreatedAt string        `json:"created_at,optional"`
	UpdatedAt string        `json:"updated_at,optional"`
}

type Entity struct {
	ID         int64  `json:"id"`
	TaskID     int64  `json:"task_id"`
	EntityName string `json:"entity_name"`
}

type EntityProp struct {
	ID        int64  `json:"id"`
	TaskID    int64  `json:"task_id"`
	EntityID  int64  `json:"entity_id"`
	PropName  string `json:"prop_name"`
	PropValue string `json:"prop_value"`
}

type ExtractTask struct {
	ID          int64   `json:"id"`
	DocIDs      []int64 `json:"doc_ids"`
	TripleIDs   []int64 `json:"triple_ids"`
	TaskName    string  `json:"task_name"`
	Remark      string  `json:"remark,optional"`
	WorkSpaceID int64   `json:"work_space_id"`
	TaskStatus  int     `json:"task_status,optional"`
	Published   bool    `json:"published"`
	CreatorID   int64   `json:"creator_id,optional"`
	CreatorName string  `json:"creator_name,optional"`
	CreatedAt   string  `json:"created_at,optional"`
	UpdatedAt   string  `json:"updated_at,optional"`
}

type GetDocumentDirListReq struct {
}

type GetDocumentDirListResp struct {
	DocumentDirs []DocumentDir `json:"document_dirs"` // 列表
}

type GetDocumentDirReq struct {
	ID int64 `json:"id"`
}

type GetDocumentDirResp struct {
	DocumentDir DocumentDir `json:"document_dir"`
}

type GetDocumentListReq struct {
	DirID int64 `json:"dir_id,optional"`
	PaginationParams
}

type GetDocumentListResp struct {
	Total      int64      `json:"total"`       // 总记录数
	Documents  []Document `json:"documents"`   // 列表
	PageSize   int        `json:"page_size"`   // 每页大小
	PageNumber int        `json:"page_number"` // 当前页码
}

type GetDocumentReq struct {
	ID int64 `json:"id"`
}

type GetDocumentResp struct {
	Document Document `json:"document"`
}

type GetEntityListReq struct {
	TaskID int64 `json:"task_id"`
	PaginationParams
}

type GetEntityListResp struct {
	Total      int64    `json:"total"`       // 总记录数
	Entities   []Entity `json:"entities"`    // 列表
	PageSize   int      `json:"page_size"`   // 每页大小
	PageNumber int      `json:"page_number"` // 当前页码
}

type GetExtractTaskListReq struct {
	WorkSpaceID int64 `json:"work_space_id"`
	PaginationParams
}

type GetExtractTaskListResp struct {
	Total        int64         `json:"total"`         // 总记录数
	ExtractTasks []ExtractTask `json:"extract_tasks"` // 列表
	PageSize     int           `json:"page_size"`     // 每页大小
	PageNumber   int           `json:"page_number"`   // 当前页码
}

type GetExtractTaskReq struct {
	ID int64 `json:"id"`
}

type GetExtractTaskResp struct {
	ExtractTask ExtractTask `json:"extract_task"`
}

type GetFileContentReq struct {
	FileID string `json:"file_id"`
}

type GetHealthResp struct {
	Result string `json:"result"`
}

type GetKnowledgeGraphWorkspaceListReq struct {
	CreatorID int64 `json:"creator_id"`
	PaginationParams
}

type GetKnowledgeGraphWorkspaceListResp struct {
	Total                    int64                     `json:"total"`                      // 总记录数
	KnowledgeGraphWorkspaces []KnowledgeGraphWorkspace `json:"knowledge_graph_workspaces"` // 列表
	PageSize                 int                       `json:"page_size"`                  // 每页大小
	PageNumber               int                       `json:"page_number"`                // 当前页码
}

type GetKnowledgeGraphWorkspaceReq struct {
	ID int64 `json:"id"`
}

type GetKnowledgeGraphWorkspaceResp struct {
	KnowledgeGraphWorkspace KnowledgeGraphWorkspace `json:"knowledge_graph_workspace"`
}

type GetOrgListReq struct {
	PaginationParams
}

type GetOrgListResp struct {
	Total         int64          `json:"total"`         // 总记录数
	Organizations []Organization `json:"organizations"` // Organizations列表
	PageSize      int            `json:"page_size"`     // 每页大小
	PageNumber    int            `json:"page_number"`   // 当前页码
}

type GetOrgReq struct {
	ID int64 `json:"id"`
}

type GetOrgResp struct {
	Organization Organization `json:"organization"`
}

type GetPropListReq struct {
	EntityID int64 `json:"entity_id"`
	PaginationParams
}

type GetPropListResp struct {
	Total      int64        `json:"total"`       // 总记录数
	Props      []EntityProp `json:"props"`       // 列表
	PageSize   int          `json:"page_size"`   // 每页大小
	PageNumber int          `json:"page_number"` // 当前页码
}

type GetRelationshipListReq struct {
	TaskID int64 `json:"task_id"`
	PaginationParams
}

type GetRelationshipListResp struct {
	Total         int64          `json:"total"`         // 总记录数
	Relationships []Relationship `json:"relationships"` // 列表
	PageSize      int            `json:"page_size"`     // 每页大小
	PageNumber    int            `json:"page_number"`   // 当前页码
}

type GetSchemaOntologyListReq struct {
	WorkSpaceID int64 `json:"work_space_id"`
	PaginationParams
}

type GetSchemaOntologyListResp struct {
	Total           int64            `json:"total"`            // 总记录数
	SchemaOntologys []SchemaOntology `json:"schema_ontologys"` // 列表
	PageSize        int              `json:"page_size"`        // 每页大小
	PageNumber      int              `json:"page_number"`      // 当前页码
}

type GetSchemaOntologyPropListReq struct {
	OntologyID int64 `json:"ontology_id"`
	PaginationParams
}

type GetSchemaOntologyPropListResp struct {
	Total               int64                `json:"total"`                 // 总记录数
	SchemaOntologyProps []SchemaOntologyProp `json:"schema_ontology_props"` // 列表
	PageSize            int                  `json:"page_size"`             // 每页大小
	PageNumber          int                  `json:"page_number"`           // 当前页码
}

type GetSchemaOntologyPropReq struct {
	ID int64 `json:"id"`
}

type GetSchemaOntologyPropResp struct {
	SchemaOntologyProp SchemaOntologyProp `json:"schema_ontology_prop"`
}

type GetSchemaOntologyReq struct {
	ID int64 `json:"id"`
}

type GetSchemaOntologyResp struct {
	SchemaOntology SchemaOntology `json:"schema_ontology"`
}

type GetSchemaTripleListReq struct {
	WorkSpaceID int64 `json:"work_space_id"`
	PaginationParams
}

type GetSchemaTripleListResp struct {
	Total         int64          `json:"total"`          // 总记录数
	SchemaTriples []SchemaTriple `json:"schema_triples"` // 列表
	PageSize      int            `json:"page_size"`      // 每页大小
	PageNumber    int            `json:"page_number"`    // 当前页码
}

type GetSchemaTripleReq struct {
	ID int64 `json:"id"`
}

type GetSchemaTripleResp struct {
	SchemaTriple SchemaTriple `json:"schema_triple"`
}

type GetUserListReq struct {
	PaginationParams
}

type GetUserListResp struct {
	Total      int64  `json:"total"`       // 总记录数
	Users      []User `json:"users"`       // User列表
	PageSize   int    `json:"page_size"`   // 每页大小
	PageNumber int    `json:"page_number"` // 当前页码
}

type GetUserReq struct {
	ID int64 `json:"id"`
}

type GetUserResp struct {
	User User `json:"user"`
}

type KnowledgeGraphWorkspace struct {
	ID                          int64  `json:"id, optional"`
	KnowledgeGraphWorkspaceName string `json:"knowledge_graph_workspace_name"`
	CreatorID                   int64  `json:"creator_id, optional"`
	CreatorName                 string `json:"creator_name, optional"`
	CreatedAt                   string `json:"created_at, optional"`
	UpdatedAt                   string `json:"updated_at, optional"`
}

type Organization struct {
	ID        int64  `json:"id, optional"`
	OrgName   string `json:"org_name"`
	CreatedAt string `json:"created_at,optional"`
	UpdatedAt string `json:"updated_at,optional"`
}

type PaginationParams struct {
	PageSize   int `json:"page_size"`
	PageNumber int `json:"page_number"`
}

type PublishExtractTaskReq struct {
	ID int64 `json:"id"`
}

type Relationship struct {
	ID               int64  `json:"id"`
	TaskID           int64  `json:"task_id"`
	SourceEntityID   int64  `json:"source_entity_id"`
	SourceEntityName string `json:"source_entity_name"`
	TargetEntityID   int64  `json:"target_entity_id"`
	TargetEntityName string `json:"target_entity_name"`
	RelationshipName string `json:"relationship_name"`
}

type SchemaOntology struct {
	ID           int64  `json:"id, optional"`
	OntologyDesc string `json:"ontology_desc"`
	OntologyName string `json:"ontology_name"`
	WorkSpaceID  int64  `json:"work_space_id"`
	CreatorID    int64  `json:"creator_id,optional"`
	CreatorName  string `json:"creator_name,optional"`
	CreatedAt    string `json:"created_at,optional"`
	UpdatedAt    string `json:"updated_at,optional"`
}

type SchemaOntologyProp struct {
	ID          int64  `json:"id, optional"`
	PropDesc    string `json:"prop_desc"`
	PropName    string `json:"prop_name"`
	WorkSpaceID int64  `json:"work_space_id"`
	OntologyID  int64  `json:"ontology_id"`
	CreatorID   int64  `json:"creator_id,optional"`
	CreatorName string `json:"creator_name,optional"`
	CreatedAt   string `json:"created_at,optional"`
	UpdatedAt   string `json:"updated_at,optional"`
}

type SchemaTriple struct {
	ID               int64  `json:"id, optional"`
	SourceOntologyID int64  `json:"source_ontology_id"`
	TargetOntologyID int64  `json:"target_ontology_id"`
	Relationship     string `json:"relationship"`
	WorkSpaceID      int64  `json:"work_space_id"`
	CreatorID        int64  `json:"creator_id, optional"`
	CreatorName      string `json:"creator_name, optional"`
	CreatedAt        string `json:"created_at, optional"`
	UpdatedAt        string `json:"updated_at, optional"`
}

type UpdateDocumentDirReq struct {
	DocumentDir DocumentDir `json:"document_dir"`
}

type UpdateDocumentReq struct {
	Document Document `json:"document"`
}

type UpdateEntityReq struct {
	Entity Entity `json:"entity"`
}

type UpdateExtractTaskReq struct {
	ExtractTask ExtractTask `json:"extract_task"`
}

type UpdateKnowledgeGraphWorkspaceReq struct {
	KnowledgeGraphWorkspace KnowledgeGraphWorkspace `json:"knowledge_graph_workspace"`
}

type UpdateOrgReq struct {
	Organization Organization `json:"organization"`
}

type UpdatePropReq struct {
	Prop EntityProp `json:"prop"`
}

type UpdateRelationshipReq struct {
	Relationship Relationship `json:"relationship"`
}

type UpdateSchemaOntologyPropReq struct {
	SchemaOntologyProp SchemaOntologyProp `json:"schema_ontology_prop"`
}

type UpdateSchemaOntologyReq struct {
	SchemaOntology SchemaOntology `json:"schema_ontology"`
}

type UpdateSchemaTripleReq struct {
	SchemaTriple SchemaTriple `json:"schema_triple"`
}

type UpdateUserReq struct {
	User User `json:"user"`
}

type UploadFileReq struct {
}

type UploadFileResp struct {
	Host     string `json:"host"`
	ObjectID string `json:"object_id"`
}

type User struct {
	ID        int64  `json:"id, optional"`
	UserCode  string `json:"user_code, optional"` // 自动生成
	OrgID     int64  `json:"org_id"`
	OrgName   string `json:"org_name, optional"` // 展示字段
	Account   string `json:"account"`
	Username  string `json:"username"`
	Password  string `json:"password, optional"`
	Phone     string `json:"phone, optional"`
	Mail      string `json:"mail, optional"`
	Enable    int    `json:"enable, optional"` // 启用状态: 1-启用，2-禁用
	Role      int    `json:"role"`             // 角色：2-普通用户，1-管理员
	Avatar    string `json:"avatar, optional"`
	CreatedAt string `json:"created_at, optional"`
	UpdatedAt string `json:"updated_at, optional"`
}
