// Code generated by goctl. DO NOT EDIT.
package types

type GetHealthResp struct {
	Result string `json:"result"`
}

type PaginationParams struct {
	PageSize   int `json:"page_size"`
	PageNumber int `json:"page_number"`
}

type Document struct {
	ID          int64  `json:"id, optional"`
	DocName     string `json:"doc_name"`
	DocDesc     string `json:"doc_desc"`
	DocPath     string `json:"doc_path"`
	DirID       int64  `json:"dir_id"`
	CreatorID   int64  `json:"creator_id,ptional"`
	CreatorName string `json:"creator_name,optional"`
	CreatedAt   string `json:"created_at,optional"`
	UpdatedAt   string `json:"updated_at,optional"`
}

type GetDocumentListReq struct {
	DirID int64 `json:"dir_id,optional"`
	PaginationParams
}

type GetDocumentListResp struct {
	Total      int64      `json:"total"`       // 总记录数
	Documents  []Document `json:"documents"`   // 列表
	PageSize   int        `json:"page_size"`   // 每页大小
	PageNumber int        `json:"page_number"` // 当前页码
}

type GetDocumentReq struct {
	ID int64 `json:"id"`
}

type GetDocumentResp struct {
	Document Document `json:"document"`
}

type CreateDocumentReq struct {
	Document Document `json:"document"`
}

type UpdateDocumentReq struct {
	Document Document `json:"document"`
}

type DeleteDocumentsReq struct {
	IDs []int64 `json:"ids"`
}

type DocumentDir struct {
	ID        int64         `json:"id, optional"`
	DirName   string        `json:"dir_name"`
	ParentID  int64         `json:"parent_id"`
	Children  []DocumentDir `json:"children"`
	SortIndex int           `json:"sort_index"`
	Remark    string        `json:"remark"`
	CreatedAt string        `json:"created_at,optional"`
	UpdatedAt string        `json:"updated_at,optional"`
}

type GetDocumentDirListReq struct {
}

type GetDocumentDirListResp struct {
	DocumentDirs []DocumentDir `json:"document_dirs"` // 列表
}

type GetDocumentDirReq struct {
	ID int64 `json:"id"`
}

type GetDocumentDirResp struct {
	DocumentDir DocumentDir `json:"document_dir"`
}

type CreateDocumentDirReq struct {
	DocumentDir DocumentDir `json:"document_dir"`
}

type UpdateDocumentDirReq struct {
	DocumentDir DocumentDir `json:"document_dir"`
}

type DeleteDocumentDirsReq struct {
	IDs []int64 `json:"ids"`
}

type UploadFileReq struct {
}

type UploadFileResp struct {
	Host     string `json:"host"`
	ObjectID string `json:"object_id"`
}

type GetFileContentReq struct {
	FileID string `json:"file_id"`
}

type Organization struct {
	ID        int64  `json:"id, optional"`
	OrgName   string `json:"org_name"`
	CreatedAt string `json:"created_at,optional"`
	UpdatedAt string `json:"updated_at,optional"`
}

type GetOrgListReq struct {
	PaginationParams
}

type GetOrgListResp struct {
	Total         int64          `json:"total"`         // 总记录数
	Organizations []Organization `json:"organizations"` // Organizations列表
	PageSize      int            `json:"page_size"`     // 每页大小
	PageNumber    int            `json:"page_number"`   // 当前页码
}

type GetOrgReq struct {
	ID int64 `json:"id"`
}

type GetOrgResp struct {
	Organization Organization `json:"organization"`
}

type CreateOrgReq struct {
	Organization Organization `json:"organization"`
}

type UpdateOrgReq struct {
	Organization Organization `json:"organization"`
}

type DeleteOrgsReq struct {
	Ids []int64 `json:"ids"`
}

type User struct {
	ID        int64  `json:"id, optional"`
	UserCode  string `json:"user_code, optional"` // 自动生成
	OrgID     int64  `json:"org_id"`
	OrgName   string `json:"org_name, optional"` // 展示字段
	Account   string `json:"account"`
	Username  string `json:"username"`
	Password  string `json:"password, optional"`
	Phone     string `json:"phone, optional"`
	Mail      string `json:"mail, optional"`
	Enable    int    `json:"enable, optional"` // 启用状态: 1-启用，2-禁用
	Role      int    `json:"role"`             // 角色：2-普通用户，1-管理员
	Avatar    string `json:"avatar, optional"`
	CreatedAt string `json:"created_at, optional"`
	UpdatedAt string `json:"updated_at, optional"`
}

type GetUserListReq struct {
	PaginationParams
}

type GetUserListResp struct {
	Total      int64  `json:"total"`       // 总记录数
	Users      []User `json:"users"`       // User列表
	PageSize   int    `json:"page_size"`   // 每页大小
	PageNumber int    `json:"page_number"` // 当前页码
}

type GetUserReq struct {
	ID int64 `json:"id"`
}

type GetUserResp struct {
	User User `json:"user"`
}

type CreateUserReq struct {
	User User `json:"user"`
}

type UpdateUserReq struct {
	User User `json:"user"`
}

type DeleteUsersReq struct {
	Ids []int64 `json:"ids"`
}
