version: "3.5"
services:
  deepkg_mysql:
    image: amd64/mysql:5.7.32
    command: [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_general_ci',
    ]
    environment:
        MYSQL_ROOT_PASSWORD: deepkg_db_pwd
        MYSQL_DATABASE: deepkg_db
        TZ: Asia/Shanghai
    container_name: deepkg_db_dev
    logging:
        driver: "json-file"
        options:
            max-size: "50m"
            max-file: "1"
    ports:
        - 3324:3306
    volumes:
        - ./data/mysql:/var/lib/mysql
        - ../model/schema:/docker-entrypoint-initdb.d/
  deepkg_minio:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    ports:
        - 9003:9000
    environment:
        MINIO_ACCESS_KEY: minio_access_key
        MINIO_SECRET_KEY: minio_secret_key
    container_name: deepkg_minio_dev
    logging:
        driver: "json-file"
        options:
            max-size: "50m"
            max-file: "1"
    volumes:
        - ./data/minio:/data
    command: ["server", "/data"]
  deepkg_redis:
    image: redis:alpine3.13
    container_name: deepkg_redis
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
        - ./redis.conf:/usr/local/etc/redis/redis.conf
        # - ./data/redis/data:/data
        # - ./data/redis/logs:/logs
    logging:
        driver: "json-file"
        options:
            max-size: "50m"
            max-file: "1"
    ports:
        - 6379:6379